Django51/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('miya.urls', namespace='ma')),
    url(r'^index/', include('miya.urls'))
]

miya/urls.py
from django.conf.urls import url

from miya import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^GoodsShow/(\d+)/$', views.GoodsShow, name='GoodsShow'),
    url(r'^logout/$', views.logout, name='logout'),
]

miya/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    img = models.CharField(max_length=100, default='title.ico')
    tel = models.CharField(max_length=20, unique=True)
    token = models.CharField(max_length=256, default='')


class Wheel(models.Model):
    img = models.CharField(max_length=50)


class Goods(models.Model):
    goodsid = models.IntegerField()
    img = models.CharField(max_length=100)
    tite = models.CharField(max_length=256)
    news = models.DecimalField(max_digits=7, decimal_places=2)
    old = models.DecimalField(max_digits=7, decimal_places=2)
    huy = models.CharField(max_length=100)
    btn = models.CharField(max_length=50)


class TypeGoods(models.Model):
    img1 = models.CharField(max_length=100)
    img2 = models.CharField(max_length=100)
    img3 = models.CharField(max_length=100)
    img4 = models.CharField(max_length=100)

    titt1 = models.CharField(max_length=256)
    titt2 = models.CharField(max_length=256)
    titt3 = models.CharField(max_length=256)

    newss1 = models.DecimalField(max_digits=7, decimal_places=2)
    newss2 = models.DecimalField(max_digits=7, decimal_places=2)
    newss3 = models.DecimalField(max_digits=7, decimal_places=2)

    old1 = models.DecimalField(max_digits=7, decimal_places=2)
    old2 = models.DecimalField(max_digits=7, decimal_places=2)
    old3 = models.DecimalField(max_digits=7, decimal_places=2)


class SingleGoods(models.Model):
    img = models.CharField(max_length=100)
    title = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=7, decimal_places=2)


class SingleGoods2(models.Model):
    img = models.CharField(max_length=100)
    title = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=7, decimal_places=2)


class GoodsDesc(models.Model):
    goodsid = models.IntegerField()
    images = models.CharField(max_length=100)
    tite = models.CharField(max_length=256)
    title = models.CharField(max_length=256)
    ptwo = models.CharField(max_length=256)
    yahei = models.CharField(max_length=100)
    item_price = models.DecimalField(max_digits=7, decimal_places=2)
    old_price = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.CharField(max_length=100)
    reduction = models.CharField(max_length=50)
    wushi = models.CharField(max_length=100)
    selects = models.CharField(max_length=50)
    imag = models.CharField(max_length=100)
    numname = models.CharField(max_length=20)


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(GoodsDesc)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)

miya/views.py
import hashlib
import random
import time

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from miya.models import User, Wheel, Goods, TypeGoods, SingleGoods, SingleGoods2, GoodsDesc, Cart


def index(request):
    wheels = Wheel.objects.all()
    goods = Goods.objects.all()
    typegoods = TypeGoods.objects.all()
    data = {
        'wheels': wheels,
        'goods': goods,
        'typegoods': typegoods,
    }
    token = request.session.get('token')
    if token:
        user = User.objects.get(token=token)
        return render(request, 'index.html', context={
            'username': user.username,
            'img': user.img,
            'wheels': wheels,
            'goods': goods,
            'typegoods': typegoods,
        })
    else:
        return render(request, 'index.html', context=data)


def genereate_pd(password):
    md5 = hashlib.md5()
    md5.update(password.encode('utf-8'))
    return md5.hexdigest()


def generate_token():
    token = str(time.time()) + str(random.random())
    md5 = hashlib.md5()
    md5.update(token.encode('utf-8'))
    return md5.hexdigest()


def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        tel = request.POST.get('tel')
        password = request.POST.get('password')
        u_password = request.POST.get('u_password')
        if password == u_password:
            user = User()
            user.username = username
            user.password = genereate_pd(password)
            user.token = generate_token()
            user.tel = tel
            user.save()

            response = redirect('ma:index')
            request.session['token'] = user.token
            request.session.set_expiry(60)
    return response


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = genereate_pd(request.POST.get('password'))
        users = User.objects.filter(username=username).filter(password=password)
        if users.count():
            response = redirect('ma:index')
            user = users.first()
            user.token = generate_token()
            user.save()
            request.session['token'] = user.token
            request.session.set_expiry(60*10)
            return response
        else:
            return render(request, 'login.html', context={'err': '用户名或密码错误'})


def logout(request):
    request.session.flush()
    return redirect('ma:index')



def cart(request):
    token = request.session.get('token')
    if token:
        user = User.objects.get(token=token)
        carts = Cart.objects.filter(user=user)
        return render(request, 'cart.html', context={'img': user.img, 'username': user.username, 'carts': carts})
    else:
        return redirect('ma:login')


def GoodsShow(request, goodsid):
    singlegoods = SingleGoods.objects.all()
    singlegoods2 = SingleGoods2.objects.all()
    goodsdesc = GoodsDesc.objects.all()
    if goodsid == "1":
        goodsdesc = goodsdesc[0]
    elif goodsid == "2":
        goodsdesc = goodsdesc[1]
    elif goodsid == "3":
        goodsdesc = goodsdesc[2]
    elif goodsid == "4":
        goodsdesc = goodsdesc[3]
    elif goodsid == "5":
        goodsdesc = goodsdesc[4]

    data = {
        'singlegoods': singlegoods,
        'singlegoods2': singlegoods2,
        'goodsdesc': goodsdesc,

    }
    token = request.session.get('token')
    if token:
        user = User.objects.get(token=token)
        return render(request, 'GoodsShow.html', context={
            'username': user.username,
            'img': user.img,
            'singlegoods': singlegoods,
            'singlegoods2': singlegoods2,
            'goodsdesc': goodsdesc,
        })
    else:

        return render(request, 'GoodsShow.html', context=data)

templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>

</head>
<body>
<!--主体内容-->
<div class="register">
    <div class="zcLogo">
        <a href="{% url 'ma:index' %}">
            <img src="{% static 'img/miya.jpg' %}">
        </a>
    </div>
    <div class="bjtp">
        <img src="{% static 'imag/bjtp.jpg' %}">
    </div>
    <div class="zhuce">
        <div class="zhuceTop">
            <span class="zctLeft">登录蜜芽</span>
            <span class="zctRight">
						<i>还没有蜜芽账号？</i>
						<a href="{% url 'ma:register' %}" target="_blank">30秒注册</a>
					</span>
        </div>
        <!--表单-->
        <form class="form" action="{% url 'ma:login' %}" method="post">
            {% csrf_token %}
            <input type="text" id="haoma" placeholder="用户名" class="text" name="username"/>
            <p class="kong">用户名不能为空</p>
            <p class="kongkong">用户名不存在</p>

            <input type="password" id="password" class="pass" placeholder="密码" name="password"/>
            <p class="kong1">密码不能为空</p>
            <p class="kong1kong1">密码错误</p>
            <div class="yan">
                <input type="text" id="yzm" placeholder="输入验证码" class="yam"/>
                <input type="text" id="code1" value="" class="code"/>
                <a href="#" id="look">看不清</a>
                <p class="kong3">输入的验证码错误</p>
            </div>
            <p class="zdong">
                <input checked="checked" id="agreeuser" type="checkbox" class="gou">自动登入
                <span class="wj">
							忘记密码？
						</span>
            </p>
            <p class="tiqiao">
                <input type="submit" value="登录" class="go" id="come"/>
            </p>
        </form>
    </div>
</div>

<!--尾部-->
<div class="reglast">
    Copyright ©2016 北京花旺在线商贸有限公司 Miyabaobei.com 保留一切权利。客服热线： 400-789-2000。京ICP证140430号 京ICP备14006215号
</div>
</body>
</html>

templates/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>登录 - 蜜芽，中国领先的进口母婴限时特卖商城</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/zhuce.js' %}"></script>

</head>
<body>
<!--主体内容-->
<div class="register">
			<div class="zcLogo">
				<a href="{% url 'ma:index' %}"><img src="{% static 'img/miya.jpg' %}"></a>
			</div>
			<div class="bjtp">
				<img src="{% static 'imag/df528a2a915203fefa34035f08343ebb884536665.png' %}">
			</div>
			<div class="zhuce">
				<div class="zhuceTop">
					<span class="zctLeft">登入蜜芽</span>
					<span class="zctRight">
						<i>还没有蜜芽账号？</i>
						<a href="{% url 'ma:register' %}" target="_blank">30秒注册</a>
					</span>
				</div>

				<!--表单-->
				<form class="form" action="{% url 'ma:register' %}" method="post" id="register-view">
                    {% csrf_token %}
					<input type="text" id="haoma" placeholder="手机号" class="text" name="tel">
					<p class="kong">手机号不能为空</p>
					<p class="kongkong">手机号错误</p>

					<p class="kong3">输入的验证码错误</p>
					<p class="kongg3">验证码不能为空</p>
					<div class="yan">
						<input type="text" id="yzm" placeholder="输入验证码" class="yam">
						<input type="text" id="code1" value="" class="code" style="color: rgb(127, 173, 46);">
						<a href="#" id="look">看不清</a>
					</div>

					<p class="kong2">用户名不能为空</p>
					<div class="duanxi">
						<input type="text" id="duanx" class="text" placeholder="用户名" name="username">
{#						<a href="#" class="get" id="get">获取短信验证码</a>#}
					</div>

					<input type="password" id="password" class="pass" placeholder="密码" name="password">
					<p class="kong1">长度为6-14个字符，建议使用字母加数字或符号组合</p>
					<p class="kong1kong1">密码错误</p>


					<input type="password" id="passwords" class="passs" placeholder="确认密码" name="u_password">
					<p class="kongg2">长度为6-14个字符，建议使用字母加数字或符号组合</p>
					<p class="kong2kong2">密码不一致</p>

					<!--<p class="zdong">
						<input checked="checked" id="agreeuser"  type="checkbox" class="gou">自动登入
						<span class="wj">
							忘记密码？
						</span>
					</p>-->
					<p class="jieshou">
						<input checked="checked" id="agreeuser" type="checkbox" class="gou">我已阅读并接受<span>《蜜芽服务条款》</span>
					</p>
					<p class="tiqiao">
						<button type="button" class="go" id="come">注册</button>
					</p>
				</form>
			</div>
		</div>

<!--尾部-->
<div class="reglast">
    Copyright ©2016 北京花旺在线商贸有限公司 Miyabaobei.com 保留一切权利。客服热线： 400-789-2000。京ICP证140430号 京ICP备14006215号
</div>
</body>
</html>